openapi: 3.0.3
info:
  title: REST VTEX
  version: 2.0.5
  description: Documentação da API responsável pela integração de operações de crédito e clientes entre o ERP TOTVS Protheus e o E-Commerce VTEX.
  # summary: Integração de operações de crédito e clientes
  contact:
    name: Suporte TI
    email: suporteti@comercialqueiroz.com.br
  x-logo:
    url: '/rest-vtex/assets/rest-vtex-logo.png'
    # backgroundColor: '#FFFFFF'
    altText: 'REST VTEX logo'
    href: 'https://crysataide.github.io/rest-vtex/'
servers:
  - url: https://wkrtswcddl.execute-api.us-east-2.amazonaws.com/vtex/rest
    description: Produção
  # - url: https://htztymyfp1.execute-api.us-east-2.amazonaws.com/hom/rest
  #   description: Homologação
paths:
  /vtex/creditLimit/{document}:
    get:
      tags:
        - Cliente
      parameters:
        - in: path
          name: document
          required: true
          schema:
            type: string
            example: "00000000000"
          allowReserved: true
      summary: Limite de crédito
      operationId: creditLimit
      description: Consulta informações de crédito do cliente com base no CPF/CNPJ
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditLimitResponse'
        '204':
          description: No Content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                  message: "Cliente não encontrado"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                noParameter:
                  summary: Parâmetro não informado na URL
                  value:
                    message: Parâmetro não informado
                noBody:
                  summary: Corpo da requisição não informado
                  value:
                    message: Body não informado
                noProperty:
                  summary: Propriedade obrigatória não informada
                  value:
                    message: Propriedade '{property}' não informada
  /vtex/customer:
    patch:
      tags:
        - Cliente
      summary: Sincroniza cliente
      description: Cria ou atualiza o cadastro de um cliente pessoa jurídica no ERP. Quando `requestedAnalysis` for igual a `true`, também será solicitada uma análise de crédito para o cliente.
      operationId: syncCustomer
      requestBody:
        required: true
        description: Dados cadastrais e comerciais do cliente pessoa jurídica.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerRequest'
      responses:
        '200':
          description: Cliente sincronizado com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
        '400':
          description: Requisição inválida ou dados insuficientes para sincronização.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                noBody:
                  summary: Corpo da requisição não informado
                  value:
                    message: Body não informado
                noProperty:
                  summary: Propriedade obrigatória não informada
                  value:
                    message: Propriedade '{property}' não informada
                dadosDoClienteInvalidos:
                  summary: Falha na sincronização cadastral
                  value:
                    message: "Erro na sincronização dos dados do cliente"
                analiseDeCreditoInvalida:
                  summary: Falha na solicitação da análise de crédito
                  value:
                    message: "Erro na sincronização da análise de crédito"
  /vtex/creditReserve:
    post:
      tags:
        - Reserva
      summary: Reserva de crédito
      description: Realiza a reserva de crédito do valor informado
      operationId: createCreditReserve
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditReserveRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditReserveResponse'
              examples:
                Reserva Criada:
                  value:
                    cardId: '04791601'
                    id: '000001'
                    refUrl: /rest
                    status: 'pending'
                Reserva Já Existente:
                  value:
                    message: '  Pedido já possui uma reserva'
                    id: '000001'
                    status: 'pending|authorized|confirmed|canceled'
        '204':
          description: No Content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: 'Cliente não encontrado'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                noBody:
                  summary: Corpo da requisição não informado
                  value:
                    message: Body não informado
                noProperty:
                  summary: Propriedade obrigatória não informada
                  value:
                    message: Propriedade '{property}' não informada
                erroReserve:
                  summary: Erro na reserva
                  value:
                    message: 'Ocorreu um erro na geração da reserva'
                reserveEmpty:
                  summary: Reserva zerada
                  value:
                    message: 'Valor para reserva zerado'
                insufficientBalance:
                  summary: Saldo insuficiente
                  value:
                    message: 'Saldo insuficiente para realizar a reserva'
                    balance: 0
                    value: 5000
  /vtex/authorization/{customerId}/reserve/{id}:
    get:
      tags:
        - Reserva
      summary: Consulta autorização
      description: Consulta status da transação
      operationId: transactionAuthorization
      parameters:
        - in: path
          name: customerId
          required: true
          schema:
            type: string
            example: '04791601'
          allowReserved: true
        - in: path
          name: id
          required: true
          schema:
            type: string
            example: '000131'
          allowReserved: true
      responses:
        '200':
          description: Reserva Rejeitada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reserve'
              example:
                  message: "Transação rejeitada"
                  status: "rejected"
        '202':
          description: Reserva Autorizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reserve'
              examples:
                Success:
                  value:
                    oid: '000001'
                    value: 5000
                    date: '1900-07-07T12:00:00Z'
                    status: 'authorized'
        '204':
          description: No Content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Cliente:
                  value:
                    message: Cliente não encontrado
                Reserva:
                  value:
                    message: Reserva não encontrada
                Pedido:
                  value:
                    message: Pedido nao encontrado
        '206':
          description: Reserva Pendente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reserve'
              examples:
                Success:
                  value:
                    oid: null
                    value: 0
                    date: null
                    status: 'pending'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                noParameter:
                  summary: Parâmetro não informado na URL
                  value:
                    message: Parâmetro não informado
                noBody:
                  summary: Corpo da requisição não informado
                  value:
                    message: Body não informado
                noProperty:
                  summary: Propriedade obrigatória não informada
                  value:
                    message: Propriedade '{property}' não informada
                reserveInvalid:
                  summary: Erro na reserva
                  value:
                    message: Reserva nao atualizada
  /vtex/cancellation/{customerId}/reserve/{id}:
    post:
      tags:
        - Reserva
      summary: Cancela transação
      description: Realiza o cancelamento da transação e estorna o valor.
      operationId: cancelTransaction
      parameters:
        - in: path
          name: customerId
          required: true
          schema:
            type: string
            example: '04791601'
          allowReserved: true
        - in: path
          name: id
          required: true
          schema:
            type: string
            example: '86000131'
          allowReserved: true
      responses:
        '200':
          description: Reserva Cancelada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reserve'
              examples:
                Success:
                  value:
                    oid: '000001'
                    value: 5000
                    date: '1900-07-07T12:00:00Z'
                    status: 'canceled'
        '204':
          description: No Content
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/Error'
              examples:
                Cliente:
                  value:
                    message: Cliente não encontrado.
                Reserva:
                  value:
                    message: Reserva não encontrada.
                Transação:
                  value:
                    message: Transação não encontrada.
        '400':
          description: Bad Request
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/Error'
              examples:
                noParameter:
                  summary: Parâmetro não informado na URL
                  value:
                    message: Parâmetro não informado
                noBody:
                  summary: Corpo da requisição não informado
                  value:
                    message: Body não informado
                noProperty:
                  summary: Propriedade obrigatória não informada
                  value:
                    message: Propriedade '{property}' não informada
  /vtex/confirmation/{customerId}/reserve/{id}:
    post:
      tags: 
        - Reserva
      summary: Confirma transação
      description: Realiza a confirmação da transação
      operationId: confirmTransaction
      parameters:
        - in: path
          name: customerId
          required: true
          schema:
            type: string
            example: '04791601'
          allowReserved: true
        - in: path
          name: id
          required: true
          schema:
            type: string
            example: '86000131'
          allowReserved: true
      responses:
        '202':
          description: Reserva Autorizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reserve'
              examples:
                Success:
                  value:
                    oid: '000001'
                    value: 5000
                    date: '1900-07-07T12:00:00Z'
                    status: 'confirmed'
        '204':
          description: No Content
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Cliente:
                  value:
                    message: Cliente não encontrado
                Reserva:
                  value:
                    message: Reserva não encontrada
                Transação:
                  value:
                    message: Transação não encontrada
        '400':
          description: Bad Request
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                noParameter:
                  summary: Parâmetro não informado na URL
                  value:
                    message: Parâmetro não informado
                noBody:
                  summary: Corpo da requisição não informado
                  value:
                    message: Body não informado
                noProperty:
                  summary: Propriedade obrigatória não informada
                  value:
                    message: Propriedade '{property}' não informada
  /vtex/order/interest-rate:
    post:
      tags: 
        - Pedido
      summary: Consulta juros
      description: Consulta juros da condição de pagamento escolhida pelo cliente e retorna os items com o acréscimo rateado
      operationId: interestRate
      requestBody:
        required: true
        description: "`requestBody` retirado da documentação oficial da VTEX - [Tax Services](https://developers.vtex.com/docs/guides/tax-services-specification#update-orderform)"
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InterestRateRequest'
      responses:
        '200':
          description: Resposta da solicitação enviada pelo Checkout
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InterestRateResponse'
        '400':
          description: Bad Request
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                noBody:
                  summary: Corpo da requisição não informado
                  value:
                    message: Body não informado
                noProperty:
                  summary: Propriedade obrigatória não informada
                  value:
                    message: Propriedade '{property}' não informada
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: |
        O valor do header **Authorization** deve ser composto por:

        `Basic Base64(<usuário>:<senha>)`

        Exemplo:

        `Authorization: Basic dXN1YXJpbzpzZW5oYQ==`
  schemas:
    CreditReserveRequest:
      type: object
      required:
        - customerId
        - paymentCondition
        - orderId
        - value
        - requestId
      properties:
        customerId:
          type: string
          description: "Identificador único do cliente"
          example: "04791601"
        paymentCondition:
          type: string
          minLength: 3
          maxLength: 3
          description: "Identificador único da condição de pagamento escolhida"
          example: "011"
        orderId:
          type: string
          description: "Identificador do pedido"
          example: '1643890500037-01'
        value:
          type: number
          format: double
          description: "Valor da reserva em centavos"
          example: 50000
        requestId:
          type: string
          description: "Identificador da requisição"
          example: "50E828C435434B1D8A7CA8AB93AFF39F"
    CreditLimitResponse:
      type: object
      required:
        - customerId
        - availableBalance
        - creditLimit
      properties:
        customerId:
          type: string
          description: Identificador único do cliente
          example: '04791601'
        availableBalance:
          type: number
          description: "Saldo disponível atual para utilização"
          example: 1000000
        creditLimit:
          type: number
          description: "Valor total do limite originalmente concedido"
          example: 1000000
        paymentConditions:
          type: array
          description: "Informações das condições de pagamento do cliente"
          items:
            - $ref: "#/components/schemas/CustomerConditions1"
            - $ref: "#/components/schemas/CustomerConditions2"
    CustomerRequest:
      type: object
      required:
        - customerId
        - corporateName
        - tradeName
        - email
        - document
        - stateRegistration
        - homePhone
        - requestedAnalysis
        - address
      properties:
        customerId:
          type: string
          format: uuid
          description: Identificador único do cliente na VTEX.
          example: "12f26a2d-e9eb-4e76-8ec3-400444be7bc5"
        corporateName:
          type: string
          description: Razão social do cliente.
          example: COMUNICACAO LTDA
        tradeName:
          type: string
          description: Nome fantasia do cliente.
          example: COMUNI MAIS
        email:
          type: string
          description: Endereço de e-mail corporativo do cliente.
          example: comunimais@corporate.com
        document:
          type: string
          description: CNPJ do cliente, com ou sem formatação.
          example: "99.999.999/9999-99"
        stateRegistration:
          type: string
          description: Inscrição estadual do cliente
          example: 99.999.999-9
        homePhone:
          type: string
          description: Número de telefone principal do cliente, incluindo o DDD.
          example: "11999999999"
        requestedAnalysis:
          type: boolean
          description: Indica se deve ser solicitada uma análise de crédito após a sincronização cadastral.
          example: true
        address:
          $ref: "#/components/schemas/CustomerAddress"
    CustomerAddress:
      type: object
      description: "Informações de endereço do cliente"
      required:
        - postalCode
        - state
        - city
        - neighborhood
        - street
        - number
      properties:
        postalCode:
          type: string
          description: CEP do endereço, com ou sem formatação.
          example: "03310-000"
        state:
          type: string
          minLength: 2
          maxLength: 2
          description: Sigla da unidade federativa.
          example: SP
        city:
          type: string
          description: Município do endereço.
          example: "São Paulo"
        neighborhood:
          type: string
          description: Bairro do endereço.
          example: "Tatuapé"
        street:
          type: string
          description: Logradouro do endereço.
          example: "R. do Tatuapé"
        number:
          type: string
          description: Número do imóvel.
          example: "999"
        complement:
          type: string
          description: "Complemento do endereço"
          example: "Sala 10"
        reference:
          type: string
          description: "Ponto de referência do endereço"
          example: "Próximo ao shopping"
    CustomerConditions1:
      type: object
      properties:
        id:
          type: string
          description: Identificador único da condição de pagamento
          example: "010"
        caption:
          type: string
          description: "Texto exibido ao consumidor no checkout"
          example: Crédito Queiroz 07 Dias
        amount:
          type: number
          description: Percentual de acréscimo que a condição de pagamento aplica
          example: 0
        installment:
          type: integer
          description: Quantidade de parcelas que a condição de pagamento aplica
          example: 1
        active:
          type: boolean
          description: Indica se a condição está disponível
          example: true
    CustomerConditions2:
      type: object
      properties:
        id:
          type: string
          description: Identificador único da condição de pagamento
          example: "011"
        caption:
          type: string
          description: "Texto exibido ao consumidor no checkout"
          example: Crédito Queiroz 07/14 Dias
        amount:
          type: number
          description: Percentual de acréscimo que a condição de pagamento aplica
          example: 0.70
        installment:
          type: integer
          description: Quantidade de parcelas que a condição de pagamento aplica
          example: 2
        active:
          type: boolean
          description: Indica se a condição está disponível
          example: true
    CustomerResponse:
      type: object
      required:
        - id
        - balance
        - totalBalance
      properties:
        id:
          type: string
          description: Código do cliente gerado ou localizado no ERP.
          example: '00000101'
        balance:
          type: integer
          format: int64
          description: Crédito disponível para utilização, expresso em centavos.
          example: 1000000
        totalBalance:
          type: integer
          format: int64
          description: Limite total de crédito aprovado para o cliente, expresso em centavos.
          example: 1000000
    CreditReserveResponse:
      type: object
      properties:
        id:
          type: string
          description: "ID único da reserva."
          example: '000001'
        cardId:
          type: string
          description: "ID único do cliente."
          example: '04791601'
        refUrl:
          type: string
          description: "URL de referência da transação."
          example: "/rest/vtex/creditReserve"
        status:
          type: string
          description: "Status da transação"
          example: "peding"
        message:
          type: string
          example: "string"
    InterestRateRequest:
      type: object
      description: Body enviado pela VTEX pelo Checkout API
      properties:
        orderFormId:
          type: string
          description: Identificador único do formulário do pedido
          example: "e5098ad8c4jk490bb2f6f03400ac1413"
        salesChannel:
          type: string
          description: Identificador único do canal de vendas
          example: "1"
        items:
          type: array
          description: |
            Lista de objetos que representam os produtos do pedido, onde `dockId` é um campo que
            se refere à identificação no sistema de logística que contém informações sobre o endereço
          items:
            $ref: "#/components/schemas/InterestrateRequest-items"
        totals:
          type: array
          description: Valor total do orderForm, detalhado em impostos, frete, descontos e preços dos itens
          items:
            - allOf:
                - $ref: "#/components/schemas/InterestrateRequest-totals"
              example:
                id: Items
                name: Items Total
                value: 820
            - allOf:
                - $ref: "#/components/schemas/InterestrateRequest-totals"
              example:
                id: Discounts
                name: Discounts Total
                value: 0
            - allOf:
                - $ref: "#/components/schemas/InterestrateRequest-totals"
              example:
                id: Shipping
                name: Shipping Total
                value: 0
            - allOf:
                - $ref: "#/components/schemas/InterestrateRequest-totals"
              example:
                id: "tax"
                name: "tax"
                value: 0
        clientEmail:
          type: string
          description: Endereço de email do cliente
          example: client@email.com
        shippingDestinations:
          type: array
          description: Lista de informações de envio
          items:
            - allOf:
                - $ref: "#/components/schemas/InterestrateRequest-shippingDestinations"
              example:
                id: 1
                country: BRA
                state: RJ
                city: Rio de Janeiro
                neighborhood: Botafogo
                postalCode: 22250-905
                street: Praia Botafogo
            - allOf:
                - $ref: "#/components/schemas/InterestrateRequest-shippingDestinations"
              example:
                id: 2
                country: BRA
                state: SP
                city: São Paulo
                neighborhood: Moema
                postalCode: 04514-000
                street: Rua Tuim
        clientData:
          $ref: "#/components/schemas/InterestrateRequest-clientData"
        paymentData:
          type: object
          description: Lista de pagamentos, com informações referentes ao pagamento do pedido
          properties:
            payments:
              type: array
              items:
                $ref: "#/components/schemas/InterestrateRequest-paymentData"
        taxApp:
          $ref: "#/components/schemas/InterestrateRequest-taxApp"
    InterestrateRequest-items:
      type: object
      properties:
        id:
          type: string
          example: "0"
        sku:
          type: string
          example: "26"
        productId:
          type: string
          example: "12"
        ean:
          type: string
          example: "12345678909123"
        refId:
          type: string
          example: "3432"
        categoryId:
          type: string
          example: "3"
        unitMultiplier:
          type: integer
          example: 1
        measurementUnit:
          type: string
          example: "un"
        targetPrice:
          type: number
          example: 8.2
        itemPrice:
          type: number
          example: 8.2
        quantity:
          type: integer
          example: 1
        discountPrice:
          type: number
          example: 0
        dockId:
          type: string
          example: "1125a08"
        freightPrice:
          type: number
          example: 0
        brandId:
          type: string
          example: "2000002"
        taxCode:
          type: string
          example: "PC040210"
        sellerId:
          type: string
          example: "1"
        shippingDestinationId:
          type: integer
          example: 1
    InterestrateRequest-totals:
      type: object
      properties:
        id:
          type: string
          example: string
        name:
          type: string
          example: string
        value:
          type: number
          example: 0.0
    InterestrateRequest-shippingDestinations:
      type: object
      properties:
        id:
          type: integer
          example: 0
        country:
          type: string
          example: string
        state:
          type: string
          example: string
        city:
          type: string
          example: string
        neighborhood:
          type: string
          example: string
        postalCode:
          type: string
          example: string
        street:
          type: string
          example: string
    InterestrateRequest-clientData:
      type: object
      description: Informações sobre o cliente que fez o pedido
      properties:
        email:
          type: string
          example: client@email.com
        document:
          type: string
          example: "12345678909"
        documentType:
          type: string
          example: cpf
        clientProfileData:
          type: string
          example: "12345678000100"
        stateInscription:
          type: string
          example: 12345678"
    InterestrateRequest-paymentData:
      type: object
      properties:
        paymentSystem:
          type: string
          example: "2"
        bin:
          type: string
          nullable: true
          example: null
        referenceValue:
          type: number
          example: 820
        value:
          type: number
          example: 820
        installments:
          type: integer
          nullable: true
          example: null
    InterestrateRequest-taxApp:
      type: object
      description: Objeto com campos personalizados específicos para a aplicação fiscal
      properties:
        fields:
          type: object
          properties:
            isTradeIn:
              type: string
              example: Yes
            productuid:
              type: string
              example: "15216842581"
            quoteuid:
              type: string
              example: "29882961591"
            condition:
              type: string
              example: working
            tradeInPrice:
              type: string
              example: "220.00"
            title:
              type: string
              example: ROG Phone II 512GB
            productIdApplied:
              type: string
              example: "404"
            uid:
              type: string
              example: "29882961591"
            taxBase:
              type: string
              example: "1399.99"
        id:
          type: string
          example: tradeincart
        major:
          type: integer
          example: 1
    InterestRateResponse:
      type: object
      properties:
        id:
          type: string
          description: índice do SKU no array de itens enviado pelo corpo da requisição
          example: "1"
        taxes:
          type: array
          items:
            type: object
            properties: 
              name:
                type: string
                description: Nome do imposto que aparecerá no checkout
                example: Juros da condicao escolhida
              description:
                type: string
                description: Campo informativo, que não aparece no storefront
                example: "Juros aplicados ao item de acordo com a condicao de pagamento selecionada."
              value:
                type: number
                description: Valor numérico absoluto que será adicionado ao preço original
                example: 0.19
    Reserve:
      type: object
      properties:
        oid:
          type: string
          nullable: true
          description: "ID único da reserva."
          example: '000001'
        value:
          type: number
          description: "Valor em centávos."
          example: 5000
        date:
          type: string
          nullable: true
          description: "Data/hora (ISO 8601)."
          example: '1900-07-07T12:00:00Z'
        status:
          type: string
          description: "Status da transação."
          example: "pending"
          enum:
            - pending
            - authorized
            - confirmed
            - canceled
            - rejected
        message:
          type: string
          example: "string"
    Error:
      type: object
      properties:
        message:
          type: string
          example: Documento inválido
        balance:
          type: integer
          example: 5000
        value:
          type: integer
          example: 5000
security:
  - basicAuth: []
tags:
  - name: Cliente
    description: Consultas relacionadas ao cliente e limite de crédito
  - name: Reserva
    description: Operações de reserva, autorização, confirmação e cancelamento
  - name: Pedido
    description: Operações para consulta de juros